### ISSUE TITLE
Unable to upload Cloudinary if no directory outside of media

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tina-graphql-gateway#289]
## Description

My Cloudinary account does not have any directories, so when you try and upload from a root folder, you receive the following error: 

### Steps to reproduce

1. Integrate the cloudinary package.
2. Attempt to upload without a folder using media manager.
3. Error received.

```
TypeError: Cannot destructure property 'directory' of 'req.body' as it is undefined.
    at uploadMedia (/Users/jperkins/development/tina-cloud-starter/node_modules/next-tinacms-cloudinary/dist/handlers.js:43:10)
```

### Expected result

Be able to upload without a directory. 

### Actual result

```
TypeError: Cannot destructure property 'directory' of 'req.body' as it is undefined.
    at uploadMedia (/Users/jperkins/development/tina-cloud-starter/node_modules/next-tinacms-cloudinary/dist/handlers.js:43:10)
```

Upload fails
What actually happened?

#### Tinacms Package Versions

    ─ next-tinacms-cloudinary@0.1.2
    ─ tinacms@0.31.0

**Comment by DirtyF** [comment]
Simialr, I created a tina-cloud-starter folder on Cloudinary, so the folder was empty and got an "upload failed" alert when I tried to upload an image in this folder.

**Comment by jbevis** [comment]
cc @logan-anderson

**Comment by DirtyF** [comment]
Still getting the same error after uploading packages:

```
TypeError: Cannot destructure property 'directory' of 'req.body' as it is undefined.
    at uploadMedia (/Users/frank/github/tina/starters/tina-cloud-starter/node_modules/next-tinacms-cloudinary/dist/handlers.js:43:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```
